//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseDetail
    {
        public int SerialNo { get; set; }
        public string ReferenceNo { get; set; }
        public string DoctorCode { get; set; }
        public bool InsuranceStatus { get; set; }
        public string InsuranceNo { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string Gender { get; set; }
        public string AllergiesInfo { get; set; }
        public string CaseDetail1 { get; set; }
        public byte[] PreviousPrescription { get; set; }
        public byte[] CaseSpecificImages { get; set; }
    }
}
