//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPDManagementEntities : DbContext
    {
        public OPDManagementEntities()
            : base("name=OPDManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoctorMaster> DoctorMasters { get; set; }
        public virtual DbSet<CaseDetail> CaseDetails { get; set; }
        public virtual DbSet<AvaibilityMaster> AvaibilityMasters { get; set; }
        public virtual DbSet<OPDManagement> OPDManagements { get; set; }
    }
}
